links:
  - from:
      repo: grantbirki/ruby-template
      path: script/bootstrap
    to:
      repo: grantbirki/ldap-api
      path: script/bootstrap
  - from:
      repo: grantbirki/ruby-template
      path: .github/CODEOWNERS
    to:
      repo: grantbirki/ldap-api
      path: .github/CODEOWNERS
  - from:
      repo: grantbirki/ruby-template
      path: .github/copilot-instructions.md
    to:
      repo: grantbirki/ldap-api
      path: .github/copilot-instructions.md
